// packages/reporter-html/src/App.svelte
<nav>
	{#each suites as [file, stages]}
		<a href={encodeURIComponent(file)}>{file}</a>
	{/each}
</nav>

<SuiteReport class="report" name={name} stages={stages}/>

<script lang="ts">
import type { ESBenchResult } from "@esbench/core/client";
import SuiteReport from "./SuiteReport.svelte";

export let result: ESBenchResult;

const suites = Object.entries(result);

const [name, stages] = suites[0];
</script>

<style>
nav {
    width: 320px;
}

.report {
	flex: 1;
}

a {
    padding: 10px;

	text-decoration: none;
	color: inherit;
}
</style>

// reporter-html/src/App.vue
<template>
	<nav :class='$style.nav'>
		<h2>Suite Name</h2>
		<a
			v-for='name of names'
			:key='name'
			:class='[$style.link, selected == name && $style.active]'
			:href='"#" + encodeURIComponent(name)'
		>
			{{ name }}
		</a>
	</nav>

	<SuiteReport
		v-if='toolchains'
		:class='$style.report'
		:name='selected'
		:result='toolchains'
	/>

	<main v-else>
		<h1 :class='$style.error'>Suite Not Found</h1>
	</main>
</template>

<script setup lang="ts">
import type { ESBenchResult } from "esbench";
import { computed, shallowRef } from "vue";
import SuiteReport from "./SuiteReport.vue";

interface AppProps {
	result: ESBenchResult;
}

const props = defineProps<AppProps>();
const names = Object.keys(props.result);

function getSuiteName() {
	return decodeURIComponent(location.hash.slice(1));
}

const initName = getSuiteName() || names[0];

const selected = shallowRef(initName);

const toolchains = computed(() => props.result[selected.value]);

window.addEventListener("hashchange", () => {
	selected.value = getSuiteName();
});
</script>

<style module>
.nav {
    width: 320px;
    padding: 0 20px;
    background: #f6f6f7;
}

.report {
    flex: 1;
    margin-left: 20px;
}

.link {
    display: block;
    margin: 10px 0;
    text-decoration: none;
    color: inherit;
}

.active {
    color: #0077ff;
}

.error {
    color: #ef4848;
}
</style>
